// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3352.Drivetrain;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivechassisLeft;
    public static SpeedController drivechassisRight;
    public static RobotDrive drivechassisRobotDrive21;
    public static DoubleSolenoid drivechassisShifter;
    public static DoubleSolenoid catapultleftPiston;
    public static DoubleSolenoid catapultrightPiston;
    public static DoubleSolenoid pickupSolenoidpickupPiston;
    public static Relay pickupelToro;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static int compSwitch = 2;
    public static int compRelay = 1;
    public static int forwardSpeedAxis = 3;
    public static int turnSpeedAxis = 1;
    public static boolean catapultState;
    public static boolean pickupState;
    public static boolean shifterState;
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivechassisLeft = new Talon(1, 1);
	LiveWindow.addActuator("Drivechassis", "Left", (Talon) drivechassisLeft);
        
        drivechassisRight = new Talon(1, 2);
	LiveWindow.addActuator("Drivechassis", "Right", (Talon) drivechassisRight);
        
        drivechassisRobotDrive21 = new RobotDrive(drivechassisLeft, drivechassisRight);
	
        drivechassisRobotDrive21.setSafetyEnabled(true);
        drivechassisRobotDrive21.setExpiration(0.1);
        drivechassisRobotDrive21.setSensitivity(0.5);
        drivechassisRobotDrive21.setMaxOutput(1.0);
        
        drivechassisShifter = new DoubleSolenoid(1, 7, 8);      
	
        
        catapultleftPiston = new DoubleSolenoid(1, 1, 2);      
	
        
        catapultrightPiston = new DoubleSolenoid(1, 3, 4);      
	
        
        pickupSolenoidpickupPiston = new DoubleSolenoid(1, 5, 6);      
	
        
        pickupelToro = new Relay(1, 2);
	LiveWindow.addActuator("Pickup", "elToro", pickupelToro);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
